# Generated by Django 2.0.13 on 2019-05-31 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0033_auto_20190301_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enkelvoudiginformatieobject',
            options={},
        ),
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='versie',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enkelvoudiginformatieobject',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)'),
        ),
        migrations.AlterUniqueTogether(
            name='enkelvoudiginformatieobject',
            unique_together={('uuid', 'versie')},
        ),
    ]
